# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 60ce8dc932b3db885d36f11036b1b1069b714d69b179f83eb234dd92962328de2eb23a9ca62df928215a06586c0c0c3091044e7eb7f3f4275cb5a4664461ccb8

test:
  secret_key_base: 4dde2da55006afc0308d0f9f71669018db4c68dfa13206f2fcb0cfdd95a18ae711200dcaa324ea415082f551ad0c062cb7b3851590cd783c3328ed74945a7d5f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
